### ISSUE TITLE
how to use this gap_staticstic code in KMedoids Clustering?

### ISSUE THREAD

**Issue by kikiegoguma** [milesgranger/gap_statistic#1]
i have kmedoids code :

`
import numpy as np
import random

def kMedoids(D, k, tmax=100):
     # determine dimensions of distance matrix D
     m, n = D.shape

    # randomly initialize an array of k medoid indices
    M = np.sort(np.random.choice(n, k))

    # create a copy of the array of medoid indices
    Mnew = np.copy(M)

    # initialize a dictionary to represent clusters
    C = {}
    for t in xrange(tmax):
        # determine clusters, i. e. arrays of data indices
        J = np.argmin(D[:,M], axis=1)
        for kappa in range(k):
            C[kappa] = np.where(J==kappa)[0]
        # update cluster medoids
        for kappa in range(k):
            J = np.mean(D[np.ix_(C[kappa],C[kappa])],axis=1)
            j = np.argmin(J)
            Mnew[kappa] = C[kappa][j]
        np.sort(Mnew)
        # check for convergence
        if np.array_equal(M, Mnew):
            break
        M = np.copy(Mnew)
    else:
        # final update of cluster memberships
        J = np.argmin(D[:,M], axis=1)
        for kappa in range(k):
            C[kappa] = np.where(J==kappa)[0]

    # return results
    return M, C
`
i wanna use gap_statistic to K-Medoids code but i'm so confused. Please help me.
thank you

**Comment by milesgranger** [comment]
Hi. I have not created a setup.py file for this repository. However give me a day or so and I'll try and have one up. Then you'll be able to install it using `pip install git+git://github.com/milesgranger/gap_statistic.git`

So far as using in your existing code, that is more or less outside the scope of opening an issue. However all you need to pass it is exactly the same array as you would pass to regular K-means, as well as the upperbounds to how many clusters you would want to test for (as mentioned in the docstring)

**Comment by milesgranger** [comment]
Hello, I added the setup.py file and updated the README to explain how to install with pip.
