### ISSUE TITLE
gap statistic calculation incorrect?

### ISSUE THREAD

**Issue by rakshita95** [milesgranger/gap_statistic#14]
Look at this notebook, I noticed that you are calculating gap statistic as:
`gap = np.log(np.mean(refDisps)) - np.log(origDisp)`

Shouldn't it be `gap = np.mean(np.log(refDisps)) - np.log(origDisp)` instead?

**Comment by rakshita95** [comment]
Hi @milesgranger, thanks for the quick reply. I was looking at page 415 of the [same reference](http://www.web.stanford.edu/~hastie/Papers/gap.pdf) where the gap statistic is defined as follows:

<img width="477" alt="screen shot 2018-07-18 at 9 56 12 am" src="https://user-images.githubusercontent.com/29198165/42896374-942ae1e2-8a71-11e8-8819-d147d04ac3ad.png">

From the formula, it seems like they are averaging the log dispersion values across the b reference datasets rather than taking logarithm of average of dispersion?

**Comment by rakshita95** [comment]
Another suggestion:

Since real world data rarely has a clear maxima in gap statistic, this might be a useful feature to add:

<img width="471" alt="screen shot 2018-07-18 at 10 10 00 am" src="https://user-images.githubusercontent.com/29198165/42896781-ce4c27f4-8a72-11e8-84b9-2854eb83817b.png">

Anyway, thanks for this package and illustrative notebook. Its a pretty important aspect of clustering.

**Comment by milesgranger** [comment]
Great, I'll look more into this later, thanks. Feel free to open a PR yourself if you'd like, might take me a while to get around to this.

**Comment by milesgranger** [comment]
Was closed by #28
