### ISSUE TITLE
_thread

### ISSUE THREAD

**Issue by milesgranger** [milesgranger/gap_statistic#16]
@druogury

Thanks for forking this repo and participating in the open-source movement! 

Just wanted to let you know that it's bad practice to fork a repo and 'fix' bugs without letting the original maintainer know about them.

Anyways, as @rakshita95 has informed me about the incorrect gap calculation, it has since been fixed so you can remove that "Improvement" from your fork. :+1:

**Comment by druogury** [comment]
Hi @milesgranger,
I should have informed you first about the bug. I just forgot. Sorry for that.
Happy to know that I contributed to your work 👍
