### ISSUE TITLE
Could we make the clustering method a parameter?

### ISSUE THREAD

**Issue by jprobichaud** [milesgranger/gap_statistic#22]
Right now, the clustering method used is a simple k-mean but technically, the gap statistics could be computed using any clustering + distance combo.  Could we make that available (and perhaps showcase spectral-clustering as one new alternative?

**Comment by milesgranger** [comment]
You bet! Sounds like a very good idea. I'm working on adding std #18 when I have time, here and there. I'll try and get this in around the same time. :+1:
