### ISSUE TITLE
Add calculation of the alternative Gap* measure.

### ISSUE THREAD

**Issue by shaypal5** [milesgranger/gap_statistic#25]
The paper "A comparison of Gap statistic definitions with and without logarithm function" by Mohajer, Englmeier and Schmid ([link](https://core.ac.uk/download/pdf/12172514.pdf)) suggests an alternative Gap* measure, which simply does not use the logarithm function is calculations.

The authors claim this measure avoids the over-estimation of the number of clusters from which the original Gap statistics suffers, and can also suggest an optimal value for k for cases in which Gap cannot. They do warn, however, that the original Gap statistic performs better than Gap* in the case of overlapped clusters, due to its tendency to overestimate the number of clusters.

This can be interesting additional information to provide in the `gap_df` attribute after the search, for more advance users to use (those interested in investigating the results and not just taking the optimal K value found).

_Note: A pull request making this enhancement will soon be opened. :)_

**Comment by milesgranger** [comment]
Closed by #28

**Comment by shaypal5** [comment]
Just to demonstrate, Gap* outperformed Gap on the first random synthetic dataset I tried this on. In other cases it sometime doesn't get the right K, but still overshoots it be less than Gap does (which is inline with the paper I referenced in my original post, that states that Gap tends to overestimate K).

Here's an image of the five generated clusters (with the cluster centers that kmeans finds for them with k=5):
![image](https://user-images.githubusercontent.com/917954/60976061-b19d9700-a335-11e9-962d-6dba1d05761a.png)

And here are the Gap and Gap* plots, respectively:
![image](https://user-images.githubusercontent.com/917954/60976206-f45f6f00-a335-11e9-8cf8-587c55020cbc.png)

![image](https://user-images.githubusercontent.com/917954/60976230-fa555000-a335-11e9-8d9a-52aa29a4b212.png)
