### ISSUE TITLE
Add documentation of the package API and the methodology behind the method

### ISSUE THREAD

**Issue by shaypal5** [milesgranger/gap_statistic#26]
The example notebook is great, but I believe additional documentation present right in the README file welcoming visitors to the repository will help users tremendously.

This is true both to a concise explanation of the method (with references to the original paper) and the API of the package, including detailing the parameters of each relevant constructor and function.

_Note: A pull request making this enhancement will soon be opened. :)_

**Comment by milesgranger** [comment]
Closed by #28
