### ISSUE TITLE
Wrong results?

### ISSUE THREAD

**Issue by shahabh** [milesgranger/gap_statistic#37]
Just run the sample notebook without changing anything. The gap-stat values are very different than the ones showed in the sample notebook. It picked k=11 (instead k=3) as the optimal k. Can someone confirm that the code is working fine?

**Comment by milesgranger** [comment]
Did you run it multiple times? There is a bit of randomness involved. I suppose there is an issue if it is significantly different every time.

**Comment by dvukolov** [comment]
The variability in the results can be significantly reduced by increasing the number of reference datasets, with say `n_refs=100`, and by using a custom clusterer that performs multiple automatic restarts, e.g. `sklearn.cluster.KMeans(n_init=20)`. This will also lead to significantly longer runtimes, so the parameters might need to be tweaked depending on the size of each dataset.
