### ISSUE TITLE
Range of the uniform reference distribution

### ISSUE THREAD

**Issue by dvukolov** [milesgranger/gap_statistic#38]
In the original paper by Tibshirani et al., the authors consider two choices for the reference distribution:

- generate each reference feature uniformly over the range of the observed values for that feature;
- generate the reference features from a uniform distribution over a box aligned with the principal components of the data.

In the `mod.rs` file, it seems that random data is generated from a standard uniform `U[0, 1]` for all features, and not from `U[X[:, i].min(), X[:, i].max()]`. Is that approach intentional? Thanks!

**Comment by milesgranger** [comment]
Nope, but good catch. I'm in limbo between fixing that, or just removing the rust implementation altogether. Won't be able to get to it until earliest, next week. 👌

**Comment by dvukolov** [comment]
Thank you. If I understood the code correctly, the issue is not Rust-specific. In the Python version, random data is also currently sampled from a standard uniform with `np.random.random_sample()`. I don't have any Rust experience, but I could try fixing the Python part.

**Comment by milesgranger** [comment]
Great, as mentioned in #39, I'm just going to take out the Rust side of things into an optional package. Until then, if you want to work on the Python side, you can just delete this lines 43-45 in setup.py:
https://github.com/milesgranger/gap_statistic/blob/6e62f60eefa7e795a26e825242757f35e716dfb7/setup.py#L43

and of course, any tests which import the rust extension. 

Again I'll try to get time available early next week, to at least remove rust which should set you up nicely for this patch.

**Comment by milesgranger** [comment]
Reopening this just for me to remember to fix the rust side. :+1:
