### ISSUE TITLE
RuntimeWarning: divide by zero encountered in log

### ISSUE THREAD

**Issue by rtrad89** [milesgranger/gap_statistic#48]
I am encountering the following `RuntimeWarning`:
```
...\Anaconda3\lib\site-packages\gap_statistic\optimalK.py:292: RuntimeWarning: divide by zero encountered in log
log_dispersion = np.log(dispersion)
```
From what I read, the warning means `dispersion=0`, so `np.log(dispersion)` is undefined.
Despite the warning, the results are not affected as far as I see.
I am using version 2.0 of `gap-stat`, installed via `pip` within `conda`:
```
# Name                    Version                   Build  Channel
gap-stat                  2.0.0                    pypi_0    pypi
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_1
numpydoc                  0.9.2                      py_0
```

**Comment by milesgranger** [comment]
Thanks for the detailed report. :+1: 

Do you have a suggestion on how/if we should deal with it? On the surface, it seems like numpy is raising the appropriate warning.

**Comment by rtrad89** [comment]
I reproduced some older results despite the warning and thus I think the reprecussions are not drastic. Consequently, I am more inclined to say it's harmless to ignore it.
Thank you ☺
