### ISSUE TITLE
OptimalK with Rust parallel backend throws Type Error

### ISSUE THREAD

**Issue by LuisHdzK** [milesgranger/gap_statistic#49]
Hi Miles!

I've tried using Rust as parallel_backend as your jupyter notebook suggested,
But I ran into this error:
```
C:\anaconda\lib\site-packages\gap_statistic\optimalK.py in __call__(self, X, n_refs, cluster_array)
    132 
    133         # Calculate the gaps for each cluster count.
--> 134         for gap_calc_result in engine(X, n_refs, cluster_array):
    135 
    136             # Assign this loop's gap statistic to gaps

C:\anaconda\lib\site-packages\gap_statistic\optimalK.py in _process_with_rust(self, X, n_refs, cluster_array)
    338             sk_star,
    339         ) in gapstat_rs.optimal_k(
--> 340             X.astype(np.float64), cluster_array.astype(np.int64), self.n_iter, n_refs
    341         ):
    342             yield GapCalcResult(

TypeError:
```
I ran it again using the multiprocessing back end and had no issues,
I checked and the dataframe was already of float64 type,

My guess is that gapstat_rs.optimal_k is returning None or something like that

Do you know what could be causing this?

Regards,
Luis Hernandez

**Comment by milesgranger** [comment]
Thanks for the report. :+1:  

Seems that was happening because I was wrongly assuming that `X` was already a numpy array. If you convert your code to pass the dataframe as a numpy array, `gapstat(df.values, ...)`, it will work. Otherwise #50 will fix this once merged and pushed to PyPi.
