### ISSUE TITLE
optimalK invalid syntax

### ISSUE THREAD

**Issue by hanhanwu** [milesgranger/gap_statistic#7]
I got this error when I used `from gap_statistic import OptimalK`

```
"python2.7/site-packages/gap_statistic/optimalK.py", line 32
    def __init__(self, n_jobs: int=-1, parallel_backend: str='joblib') -> None:
                             ^
SyntaxError: invalid syntax
```

**Comment by milesgranger** [comment]
Hello, sorry for the trouble. This is because this new syntax is only available in Python 3; if you can, switch to the modern Python. ;)
